# Use a imagem oficial do Nginx como base
FROM nginx:alpine

# Copie o arquivo de configuração do Nginx para o contêiner
COPY nginx.conf /etc/nginx/nginx.conf

# Exponha a porta em que o Nginx irá rodar
EXPOSE 80