version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django  # Nome do Dockerfile para o Django
    expose:
      - "8000"
    volumes:
      - .:/app
    networks:
      - webnet

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx  # Nome do Dockerfile para o Nginx
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/app/staticfiles  # Mapeia o diretório de arquivos estáticos
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mapeia o arquivo de configuração do Nginx
    depends_on:
      - django
    networks:
      - webnet

networks:
  webnet:
